name: Update Competitions Data

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *' # Daily at 12:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Update competitions data
        run: node update-competitions.js
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add competitions.json
          git commit -m "Auto-update competitions data" || echo "No changes"
          git push
